### ISSUE TITLE
Understanding the child key

### ISSUE THREAD

**Issue by void-in** [kostamoisidis/TSSExamples#1]
Hi there. Really appreciate the repo for a clear cut implementation of the TPM operations. Just wanted to ask what is the child key being derived from the prime key? Our requirement is to generate the RSA key pair, persist the private key in TPM, export and send the public key to the server which can then use it to encrypt the session key. Your repo is a great help but just wanted to understand this child key from the prime key thing more clearly. Thank you very much.

**Comment by kostamoisidis** [comment]
Hey! As much as I would wish to help, I have left development of this repo and this idea in past. With it, my knowledge as well. I do believe that secondary keys are derived form the primary key (seed). The primary key is never to be revealed - Its for the TPMs eyes only. Rest of the keys are exportable. But more than that would be a pure guess on my side.

In my endeavors on this topic, I frequently visited [A Practical Guide to TPM 2.0](https://link.springer.com/book/10.1007/978-1-4302-6584-9) by Will Arthur , David Challener , Kenneth Goldman. If you want to find out more, I recommend checking it out. Good luck!

**Comment by void-in** [comment]
Thanks a lot for the pointer and no issues. Your provided help is already much appreciated.
